# Generated by Django 4.1.1 on 2025-03-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='distance',
        ),
    ]
